var refEn = {"site-map": {
	"LOCATING_FAILURE": "Did not find your location",
	"LOCATING_SUCCESS": "Your location",
	"LOADING_FAILURE": "An error occurred, zoom in and try again please",
	"LNK_OSM_EDIT": "Edit in OSM",
	"LNK_OSM_REPORT": "Report wrong information",
	"LNK_OSM_VIEW": "View POI in OpenStreetMap",
	"LNK_OPEN_WITH": "Open with App",
	"FLTR_SELECTALL": "(De)select all",
	"PDV_UNNAME": "No Name",
	"PDV_ADDRESS_UNKNOWN": "Address not known",
	"PDV_COMMUNE_UNKNOWN": "Commune not known",
	"PDV_STREET_UNKNOWN": "Street not known",
	"PDV_HOUSENUMBER_UNKNOWN": "House number not known",
	"PDV_ZIPCODE_UNKNOWN": "Zipcode not known",
	"PDV_STREET_UNKNOWN": "Street unknown",
	"PDV_ADDRESS_UNKNOWN": "Address unknown",
	"PDV_HOUSENUMBER_UNKNOWN": "?",
	"PDV_COMMUNE_UNKNOWN": "?",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Baby friendlyness",
	"PDV_TITLE_OH": "Opening hours",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "More information",
	"PDV_DIAPER_YES": "Changing table available",
	"PDV_DIAPER_NO": "No changing table available",
	"PDV_DIAPER_ROOM": "Diaper-changing room",
	"PDV_DIAPER_MALE_YES": "Changing table in the men's room",
	"PDV_DIAPER_FEMALE_YES": "Changing table in the ladies' room",
	"PDV_DIAPER_UNISEX_YES": "Changing table in the unisex toilet",
	"PDV_DIAPER_FEE_YES": "Fee for using the changing table",
	"PDV_DIAPER_FEE_NO": "No fee for using the changing table",
	"PDV_HIGHCHAIR_YES": "Highchair available",
	"PDV_HIGHCHAIR_NO": "Highchair not available",
	"PDV_HIGHCHAIR_COUNT": "highchairs available",
	"PDV_KIDSAREA_YES": "Kids area available",
	"PDV_KIDSAREA_NO": "Kids area not available",
	"PDV_KIDSAREA_INDOOR_YES": "Kids area is inside",
	"PDV_KIDSAREA_OUTDOOR_YES": "Kids area is outside",
	"PDV_KIDSAREA_SUPERVISED_YES": "Kids area is supervised",
	"PDV_KIDSAREA_FEE_YES": "Fee must be paid",
	"PDV_STROLLER_YES": "Location is stroller friendly",
	"PDV_STROLLER_LIMITED": "Location is partially stroller friendly",
	"PDV_STROLLER_NO": "Location isn't stroller friendly",
	"PDV_BABYFEEDING_YES": "Place for (breast-)feeding available",
	"PDV_BABYFEEDING_NO": "No place for (breast-)feeding available",
	"PDV_BABYFEEDING_ROOM": "Room for (breast-)feeding available",
	"PDV_BABYFEEDING_MALE_YES": "Place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_YES": "Place for women to feed a baby available",
	"PDV_BABYFEEDING_MALE_NO": "No place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_NO": "No place for women to feed a baby available",
	"PDV_OPERATOR": "Operator",
	"PDV_DESCRIPTION": "Description",
	"TOILET": "Toilet",
	"BTN_APPLY_FILTERS": "Apply filters",
	"LNK_IMPRESS": "About",
	"LNK_IMPRESS_URL": "/impressum.html#en",
	"LNK_PP_SITE": "Privacy (v.2)",
	"LNK_PP_SITE_URL": "/privacypolicy-en.html",
	"LNK_GITHUB": "On Github",
	"LNK_OSMWIKI": "OSM Wiki",
	"TB_SEARCHFIELD": "Search",
	"opening_hours": {"Mo" : "Monday", "Tu" : "Tuesday", "We" : "Wednesday", "Th" : "Thursday", "Fr" : "Friday", "Sa" : "Saturday", "Su" : "Sunday", "off" : "closed", "Jan" : "January", "Feb" : "February", "Mar" : "March", "Apr" : "April", "May" : "May", "Jun" : "June", "Jul" : "July", "Aug" : "August", "Sep" : "September", "Oct" : "October", "Nov" : "November", "Dec" : "December", "PH" : "holiday"},
	"filtername": {
		0: "Paediatricians / children's wards",
		1: "Midwifes",
		2: "Birthing centers",
		3: "Playgrounds",
		4: "Parks",
		5: "Shops for baby goods",
		6: "Shops for toys",
		7: "Shops for clothes",
		8: "Kindergartens and child care",
		9: "Zoos",
		10: "Changing tables",
		11: "Only changing tables accessible for men",
		12: "Cafés",
		13: "Restaurants"
	},
	"filtertranslations": {
		"healthcare=doctor": "Pediatrician",
		"healthcare=hospital": "Hospital",
		"healthcare=midwife": "Midwife",
		"healthcare=birthing_center": "Birthing center",
		"amenity=toilets": "Toilets",
		"amenity=cafe": "Cafe",
		"amenity=restaurant": "Restaurant",
		"amenity=kindergarten" : "Kindergarten",
		"amenity=childcare" : "Kindergarten",
		"leisure=playground": "Playground",
		"leisure=park": "Park",
		"tourism=zoo": "Zoo",
		"shop=baby_goods": "Baby goods",
		"shop=toys": "Toy store",
		"shop=clothes": "Clothes",
		"shop=chemist": "Chemist",
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "About",
	"IMPRESS_SUBTITLE": "Responsible for this website",
	"IMPRESS_COUNTRY": "Germany",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "All data available on this website is coming from OpenStreetMap. Babykarte just uses the data. We do not guarantee for the correctness of it. Through the provided links you can convey annotations to wrong or missing data to OpenStreetMap. You can also correct wrong ones or add further information by yourself."
	}
};
registerLang("en", refEn);
setLang("", "en");
