var refEn = {"site-map": {
	"LOCATING_FAILURE": "Did not find your position",
	"LOCATING_SUCCESS": "Your position",
	"LOADING_FAILURE": "An error occurred, zoom in and try again please",
	"LNK_OSM_EDIT": "Edit in OSM",
	"LNK_OSM_REPORT": "Report wrong information",
	"LNK_OSM_VIEW": "View POI in OpenStreetMap",
	"LNK_OPEN_WITH": "Open with App",
	"PDV_UNNAME": "No Name",
	"PDV_ADDRESS_UNKNOWN": "Address not known",
	"PDV_COMMUNE_UNKNOWN": "Commune not known",
	"PDV_STREET_UNKNOWN": "Street not known",
	"PDV_HOUSENUMBER_UNKNOWN": "House number not known",
	"PDV_ZIPCODE_UNKNOWN": "Zipcode not known",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Baby friendly",
	"PDV_TITLE_OH": "Opening hours",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "More information",
	"PDV_DIAPER": "Changing table(s):",
	"PDV_DIAPER_YES": "Changing table available",
	"PDV_DIAPER_BENCH": "No changing table, but bench in the restroom",
	"PDV_DIAPER_ROOM": "Diaper-changing room",
	"PDV_DIAPER_MALE": "Changing table in the men's room",
	"PDV_DIAPER_MALE_NO": "No changing table in the men's room",
	"PDV_DIAPER_MALE_UNKNOWN": "",
	"PDV_DIAPER_FEMALE": "Changing table in the ladies' room",
	"PDV_DIAPER_FEMALE_NO": "No changing table in the ladies' room",
	"PDV_DIAPER_MALE_UNKNOWN": "",
	"PDV_DIAPER_UNISEX": "Changing table in the unisex toilet",
	"PDV_DIAPER_FEE": "Fee for changing table",
	"PDV_DIAPER_FEE_NO": "No fee for changing table",
	"PDV_HIGHCHAIR_YES": "Highchair available",
	"PDV_HIGHCHAIR_NO": "Highchair not available",
	"PDV_HIGHCHAIR_COUNT": "highchairs available",
	"PDV_KIDSAREA_YES": "Kids area available",
	"PDV_KIDSAREA_NO": "Kids area not available",
	"PDV_STROLLER_YES": "Location is stroller friendly",
	"PDV_STROLLER_LIMITED": "Location is partially stroller friendly",
	"PDV_STROLLER_NO": "Location isn't stroller friendly",
	"TOILET": "Toilet",
	"BTN_APPLY_FILTERS": "Apply filters",
	"LNK_IMPRESS": "About",
	"LNK_IMPRESS_URL": "/impressum.html#en",
	"LNK_PP_SITE": "Privacy (v.1)",
	"LNK_PP_SITE_URL": "/privacypolicy-en.html",
	"LNK_GITHUB": "On Github",
	"LNK_OSMWIKI": "OSM Wiki",
	"TB_SEARCHFIELD": "Place",
	"opening_hours": {"Mo" : "Monday", "Tu" : "Tuesday", "We" : "Wednesday", "Th" : "Thursday", "Fr" : "Friday", "Sa" : "Saturday", "Su" : "Sunday", "off" : "closed", "Jan" : "January", "Feb" : "February", "Mar" : "March", "Apr" : "April", "May" : "May", "Jun" : "June", "Jul" : "July", "Aug" : "August", "Sep" : "September", "Oct" : "October", "Nov" : "November", "Dec" : "December", "PH" : "holiday"},
	"filtername": {
		0: "Paediatricians",
		1: "Midwifes",
		2: "Birthing centers",
		3: "Playgrounds",
		4: "Parks",
		5: "Shops for baby goods",
		6: "Shops for toys",
		7: "Shops for clothes",
		8: "Kindergartens",
		9: "Zoos",
		10: "Changing tables",
		11: "Cafés",
		12: "Restaurants"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "About",
	"IMPRESS_SUBTITLE": "Responsible for this website",
	"IMPRESS_COUNTRY": "Germany",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "All data available on this website is coming from OpenStreetMap. Babykarte just uses the data. We do not guarantee for the correctness of it. Through the provided links you can convey annotations to wrong or missing data to OpenStreetMap. You can also correct wrong ones or add further information by yourself."
	}
};
registerLang("en", refEn);
setLang("", "en");
