var refEn = {"site-map": {
	"LOCATING_FAILURE": "Did not find your location",
	"LOCATING_SUCCESS": "Your location",
	"LOADING_FAILURE": "An error occurred, zoom in and try again please",
	"LNK_OSM_EDIT": "Edit in OSM",
	"LNK_OSM_REPORT": "Report wrong information",
	"LNK_OSM_VIEW": "View POI in OpenStreetMap",
	"LNK_OPEN_WITH": "Open with an app",
	"FLTR_SELECTALL": "(De)select all",
	"PDV_UNNAME": "No Name",
	"PDV_ZIPCODE_UNKNOWN": "Zipcode not known",
	"PDV_STREET_UNKNOWN": "Street unknown",
	"PDV_ADDRESS_UNKNOWN": "Address unknown",
	"PDV_HOUSENUMBER_UNKNOWN": "?",
	"PDV_COMMUNE_UNKNOWN": "?",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Baby friendliness",
	"PDV_TITLE_OH": "Opening hours",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "More information",
	"PDV_DIAPER_YES": "Changing table available",
	"PDV_DIAPER_NO": "No changing table available",
	"PDV_DIAPER_ROOM": "Diaper-changing room",
	"PDV_DIAPER_MALE_YES": "in the men's room",
	"PDV_DIAPER_FEMALE_YES": "in the ladies' room",
	"PDV_DIAPER_UNISEX_YES": "in the unisex toilet",
	"PDV_DIAPER_FEE_YES": "Fee applies",
	"PDV_DIAPER_FEE_NO": "No fee applies",
	"PDV_DIAPER_UNKNOWN": "Existence of changing table unknown",
	"PDV_CHANGINGTABLE_YES": "Changing table available",
	"PDV_CHANGINGTABLE_NO": "No changing table available",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "In a multi-purpose room",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "in a diaper-changing room",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "in the men's room",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "in the ladies' room",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "in the unisex toilet",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "in the wheelchair users' room",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "right in the sales area",
	"PDV_CHANGINGTABLE_FEE_YES": "Fee applies",
	"PDV_CHANGINGTABLE_FEE_NO": "No fee applies",
	"PDV_CHANGINGTABLE_UNKNOWN": "Existence of changing table unknown",
	"PDV_HIGHCHAIR_YES": "Highchair available",
	"PDV_HIGHCHAIR_NO": "Highchair not available",
	"PDV_HIGHCHAIR_COUNT": "highchairs available",
	"PDV_HIGHCHAIR_UNKNOWN": "Existence of highchairs unknown",
	"PDV_KIDSAREA_YES": "Kids area available",
	"PDV_KIDSAREA_NO": "Kids area not available",
	"PDV_KIDSAREA_INDOOR_YES": "Kids area is inside",
	"PDV_KIDSAREA_OUTDOOR_YES": "Kids area is outside",
	"PDV_KIDSAREA_SUPERVISED_YES": "Kids area is supervised",
	"PDV_KIDSAREA_FEE_YES": "Fee must be paid",
	"PDV_KIDSAREA_UNKNOWN": "Existence of a kids' area unknown",
	"PDV_STROLLER_YES": "Location is stroller friendly",
	"PDV_STROLLER_LIMITED": "Location is partially stroller friendly",
	"PDV_STROLLER_NO": "Location isn't stroller friendly",
	"PDV_STROLLER_UNKNOWN": "Stroller friendliness unknown",
	"PDV_BABYFEEDING_YES": "Place for (breast-)feeding available",
	"PDV_BABYFEEDING_NO": "No place for (breast-)feeding available",
	"PDV_BABYFEEDING_ROOM": "Room for (breast-)feeding available",
	"PDV_BABYFEEDING_MALE_YES": "Place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_YES": "Place for women to feed a baby available",
	"PDV_BABYFEEDING_MALE_NO": "No place for men to feed a baby available",
	"PDV_BABYFEEDING_FEMALE_NO": "No place for women to feed a baby available",
	"PDV_LEISURE_PLAYGROUND": "Playground equipment",
	"PDV_PLAYGROUND_SLIDE_YES": "Slide",
	"PDV_PLAYGROUND_SWING_YES": "Swing",
	"PDV_PLAYGROUND_CLIMBINGFRAME_YES": "Climbing frame",
	"PDV_PLAYGROUND_CLIMBINGWALL_YES": "Climbing wall",
	"PDV_PLAYGROUND_SLEDDING_YES": "Sledding",
	"PDV_PLAYGROUND_SANDPIT_YES": "Sandpit",
	"PDV_PLAYGROUND_SEESAW_YES": "Seesaw",
	"PDV_PLAYGROUND_SPRINGY_YES": "Springy",
	"PDV_PLAYGROUND_PLAYHOUSE_YES": "Playhouse",
	"PDV_PLAYGROUND_ROUNDABOUT_YES": "Roundabout",
	"PDV_PLAYGROUND_MULTIPLAY_YES": "Multi play",
	"PDV_PLAYGROUND_BASKETSWING_YES": "Basket swing",
	"PDV_PLAYGROUND_STRUCTURE_YES": "Structure",
	"PDV_PLAYGROUND_ZIPWIRE_YES": "Zipwire",
	"PDV_PLAYGROUND_BALANCEBEAM_YES": "Balance beam",
	"PDV_PLAYGROUND_WATER_YES": "Water play",
	"PDV_PLAYGROUND_TRAMPOLINE_YES": "Trampoline",
	"PDV_PLAYGROUND_TEENSHELTER_YES": "Teen shelter",
	"PDV_PLAYGROUND_CHAINLADDER_YES": "Chain ladder",
	"PDV_PLAYGROUND_HOPSCOTCH_YES": "Hopscotch",
	"PDV_PLAYGROUND_CLIMBWALL_YES": "Climb wall",
	"PDV_PLAYGROUND_TUNNELTUBE_YES": "Tunnel tube",
	"PDV_PLAYGROUND_CHESSTABLE_YES": "Chess table",
	"PDV_PLAYGROUND_TREEHOUSE_YES": "Tree house",
	"PDV_PLAYGROUND_BASKETBALLBACKBOARDS_YES": "Basketball backboards",
	"PDV_PLAYGROUND_CUSHION_YES": "Cushion",
	"PDV_PLAYGROUND_SKATEEQUIPMENT_YES": "Skate equipment",
	"PDV_WHEELCHAIR_YES": "Wheeled users friendly",
	"PDV_WHEELCHAIR_NO": "Not wheeled users friendly",
	"PDV_MATERIAL_WOOD": "Made of wood",
	"PDV_MATERIAL_METAL": "Made of metal",
	"PDV_MATERIAL_STEEL": "Made of steel",
	"PDV_MATERIAL_PLASTIC": "Made of plastic",
	"PDV_MATERIAL_ROPE": "Made of ropes",
	"PDV_CAPACITY_DISABLED_YES": "Wheeled users friendly",
	"PDV_CAPACITY_DISABLED_NO": "Not wheeled users friendly",
	"PDV_BABY_YES": "Playable by babies",
	"PDV_BABY_NO": "Not playable by babies",
	"PDV_BABY_ONLY": "Predominantly made for babies",
	"PDV_SURFACE_SAND": "Surface: sand",
	"PDV_SURFACE_WOOD": "Surface: wood",
	"PDV_SURFACE_GRASS": "Surface: grass",
	"PDV_SURFACE_DIRT": "Surface is dirty",
	"PDV_SURFACE_WOODCHIPS": "Woodchiped",
	"PDV_SURFACE_CLAY": "Surface: clay",
	"PDV_SURFACE_TARTAN": "Surface: tartan",
	"PDV_SURFACE_ARTIFICIALSURF": "Surface: artificial surf",
	"PDV_SURFACE_DECOSURF": "Surface: decosurf",
	"PDV_ACCESS_YES": "Allowed use",
	"PDV_ACCESS_NO": "Forbidden use",
	"PDV_ACCESS_CUSTOMERS": "Customers only",
	"PDV_ACCESS_PRIVATE": "Private equipment",
	"PDV_OPERATOR": "Operator",
	"PDV_DESCRIPTION": "Description",
	"TOILET": "Toilet",
	"BTN_APPLY_FILTERS": "Apply filters",
	"LNK_IMPRESS": "About",
	"LNK_IMPRESS_URL": "/impressum.html#en",
	"LNK_PP_SITE": "Privacy (v.2)",
	"LNK_PP_SITE_URL": "/privacypolicy-en.html",
	"LNK_GITHUB": "On Github",
	"LNK_OSMWIKI": "OSM Wiki",
	"TB_SEARCHFIELD": "Search",
	"opening_hours": {"Mo" : "Monday", "Tu" : "Tuesday", "We" : "Wednesday", "Th" : "Thursday", "Fr" : "Friday", "Sa" : "Saturday", "Su" : "Sunday", "off" : "closed", "Jan" : "January", "Feb" : "February", "Mar" : "March", "Apr" : "April", "May" : "May", "Jun" : "June", "Jul" : "July", "Aug" : "August", "Sep" : "September", "Oct" : "October", "Nov" : "November", "Dec" : "December", "PH" : "holiday"},
	"filtername": {
		0: "Paediatricians / children's wards",
		1: "Midwifes",
		2: "Birthing centers",
		3: "Playgrounds",
		4: "Playground equipment",
		5: "Parks",
		6: "Shops for baby goods",
		7: "Shops for toys",
		8: "Shops for clothes",
		9: "Kindergartens and child care",
		10: "Zoos",
		11: "Changing tables",
		12: "Only changing tables accessible for men",
		13: "Cafés",
		14: "Restaurants"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "About",
	"IMPRESS_SUBTITLE": "Responsible for this website",
	"IMPRESS_COUNTRY": "Germany",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "All data available on this website is coming from OpenStreetMap. Babykarte just uses the data. We do not guarantee for the correctness of it. Through the provided links you can convey annotations to wrong or missing data to OpenStreetMap. You can also correct wrong ones or add further information by yourself."
	}
};
refEn["site-map"].filtertranslations = {
	"healthcare=doctor": "Pediatrician",
	"healthcare=hospital": "Hospital",
	"healthcare=midwife": "Midwife",
	"healthcare=birthing_center": "Birthing center",
	"amenity=toilets": "Toilets",
	"amenity=cafe": "Cafe",
	"amenity=restaurant": "Restaurant",
	"amenity=kindergarten" : "Kindergarten",
	"amenity=childcare" : "Kindergarten",
	"leisure=playground": "Playground",
	"leisure=park": "Park",
	"tourism=zoo": "Zoo",
	"shop=baby_goods": "Baby goods",
	"shop=toys": "Toy store",
	"shop=clothes": "Clothes",
	"shop=chemist": "Chemist",
	"shop=supermarket": "Supermarket"
}
registerLang("en", refEn);
setLang("", "en");
