var refFr = {"site-map": {
	"LOCATING_FAILURE": "N'a pas trouvé votre lieu",
	"LOCATING_SUCCESS": "Votre lieu",
	"LOADING_FAILURE": "Une erreur s'est produite, veuillez zoomer et réessayer",
	"LNK_OSM_EDIT": "Modifier dans OSM",
	"LNK_OSM_REPORT": "Signaler une information erronée",
	"LNK_OSM_VIEW": "Voir le Point d'intérêt dans OpenStreetMap",
	"LNK_OPEN_WITH": "Ouvrir avec une appli",
	"FLTR_NOTHINGSELECTED": "No filter selected. Please select one or more filters in the menu which you can open by clicking &#9776; on smaller screens. (en)",
	"FLTR_SELECTALL": "(De)sélectionnez tout",
	"PDV_UNNAME": "Sans Nom",
	"PDV_ADDRESS_UNKNOWN": "Addresse inconnue",
	"PDV_COMMUNE_UNKNOWN": "?",
	"PDV_STREET_UNKNOWN": "Rue inconnue",
	"PDV_HOUSENUMBER_UNKNOWN": "?",
	"PDV_ZIPCODE_UNKNOWN": "Code postal inconnu",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Adapté aux bébés",
	"PDV_TITLE_OH": "Horaires d'ouverture",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "Plus d'informations",
	"PDV_DIAPER_YES": "Table à langer disponible",
	"PDV_DIAPER_NO": "Pas de table à langer disponible",
	"PDV_DIAPER_LIMITED": "Limited changing facilities available. (EN)",
	"PDV_DIAPER_ROOM": "Vestiaire à langer",
	"PDV_DIAPER_MALE_YES": "dans les toilettes pour hommes",
	"PDV_DIAPER_FEMALE_YES": "dans les toilettes pour femmes",
	"PDV_DIAPER_UNISEX_YES": "dans les toilettes unisexes",
	"PDV_DIAPER_FEE_YES": "Payant",
	"PDV_DIAPER_FEE_NO": "Gratuit",
	"PDV_DIAPER_UNKNOWN": "Existence d'une table à langer inconnue",
	"PDV_CHANGINGTABLE_YES": "Table à langer disponible",
	"PDV_CHANGINGTABLE_NO": "Pas de table à langer disponible",
	"PDV_CHANGINGTABLE_LIMITED": "Limited changing facilities available. (EN)",
	"PDV_CHANGINGTABLE_LOCATION_ROOM": "Dans une salle polyvalente",
	"PDV_CHANGINGTABLE_LOCATION_DEDICATEDROOM": "dans une salle dédiée",
	"PDV_CHANGINGTABLE_LOCATION_MALETOILET": "dans les toilettes pour hommes",
	"PDV_CHANGINGTABLE_LOCATION_FEMALETOILET": "dans les toilettes pour femmes",
	"PDV_CHANGINGTABLE_LOCATION_UNISEXTOILET": "dans les toilettes unisexes",
	"PDV_CHANGINGTABLE_LOCATION_WHEELCHAIRTOILET": "dans les toilettes pour handicapés",
	"PDV_CHANGINGTABLE_LOCATION_SALESAREA": "directement dans la zone commerciale",
	"PDV_CHANGINGTABLE_FEE_YES": "Payant",
	"PDV_CHANGINGTABLE_FEE_NO": "Gratuit",
	"PDV_CHANGINGTABLE_UNKNOWN": "Existence d'une table à langer inconnue",
	"PDV_HIGHCHAIR_YES": "Chaise haute disponible",
	"PDV_HIGHCHAIR_NO": "Chaise haute non disponible",
	"PDV_HIGHCHAIR_COUNT": "chaises hautes disponibles",
	"PDV_HIGHCHAIR_UNKNOWN": "Existence de chaises hautes inconnue",
	"PDV_KIDSAREA_YES": "Espace enfants disponible",
	"PDV_KIDSAREA_NO": "Espace enfants non disponible",
	"PDV_KIDSAREA_INDOOR_YES": "Espace enfants intérieur",
	"PDV_KIDSAREA_OUTDOOR_YES": "Espace enfants extérieur",
	"PDV_KIDSAREA_SUPERVISED_YES": "Espace enfants surveillé",
	"PDV_KIDSAREA_FEE_YES": "Payant",
	"PDV_KIDSAREA_UNKNOWN": "Existence d'espaces enfants inconnue",
	"PDV_STROLLER_YES": "Le lieu est adapté aux poussettes",
	"PDV_STROLLER_LIMITED": "Le lieu est partiellement adapté aux poussettes",
	"PDV_STROLLER_NO": "Le lieu n'est pas adapté aux poussettes",
	"PDV_STROLLER_UNKNOWN": "Support aux poussettes inconnu",
	"PDV_BABYFEEDING_YES": "Lieu pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_NO": "Pas de lieu pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_ROOM": "Salle pour l'allaitement (au sein) disponible",
	"PDV_BABYFEEDING_MALE_YES": "Lieu pour les hommes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_FEMALE_YES": "Lieu pour les femmes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_MALE_NO": "Pas de lieu pour les hommes pour nourrir un bébé disponible",
	"PDV_BABYFEEDING_FEMALE_NO": "Pas de lieu pour les femmes pour nourrir un bébé disponible",
	"PDV_LEISURE_PLAYGROUND": "Équipements d'aires de jeux",
	"PDV_MINAGE_*": "Min age: %s (EN)",
	"PDV_MAXAGE_*": "Max age: %s (EN)",
	"PDV_PLAYGROUND_SLIDE_YES": "Toboggan",
	"PDV_PLAYGROUND_SWING_YES": "Balançoire",
	"PDV_PLAYGROUND_CLIMBINGFRAME_YES": "Équipement d'escalade",
	"PDV_PLAYGROUND_CLIMBINGWALL_YES": "Climbing wall (EN)",
	"PDV_PLAYGROUND_SLEDDING_YES": "Sledding (EN)",
	"PDV_PLAYGROUND_SANDPIT_YES": "Bac à sable",
	"PDV_PLAYGROUND_SEESAW_YES": "Balançoire à bascule",
	"PDV_PLAYGROUND_SPRINGY_YES": "Fauteuil à ressort",
	"PDV_PLAYGROUND_PLAYHOUSE_YES": "Petite Maisonnette",
	"PDV_PLAYGROUND_ROUNDABOUT_YES": "Tourniquet",
	"PDV_PLAYGROUND_MULTIPLAY_YES": "Multi-jeu",
	"PDV_PLAYGROUND_BASKETSWING_YES": "Panier à bascule",
	"PDV_PLAYGROUND_STRUCTURE_YES": "Structure",
	"PDV_PLAYGROUND_ZIPWIRE_YES": "Tyrolienne",
	"PDV_PLAYGROUND_BALANCEBEAM_YES": "Poutre d'équilibre",
	"PDV_PLAYGROUND_WATER_YES": "Jeux d'eau",
	"PDV_PLAYGROUND_TRAMPOLINE_YES": "Trampoline",
	"PDV_PLAYGROUND_TEENSHELTER_YES": "Abri pour enfants",
	"PDV_PLAYGROUND_CHAINLADDER_YES": "Échelle à chaîne",
	"PDV_PLAYGROUND_HOPSCOTCH_YES": "Marelle",
	"PDV_PLAYGROUND_CLIMBWALL_YES": "Mur d'escalade enfant",
	"PDV_PLAYGROUND_TUNNELTUBE_YES": "Tube de tunnel",
	"PDV_PLAYGROUND_CHESSTABLE_YES": "Table d'échecs",
	"PDV_PLAYGROUND_TREEHOUSE_YES": "Maison dans l'arbre",
	"PDV_PLAYGROUND_BASKETBALLBACKBOARDS_YES": "Panneaux de basket-ball",
	"PDV_PLAYGROUND_CUSHION_YES": "Château gonflable",
	"PDV_PLAYGROUND_SKATEEQUIPMENT_YES": "Équipement de patinage",
	"PDV_WHEELCHAIR_YES": "Accessible by wheelchair (EN)",
	"PDV_WHEELCHAIR_NO": "Not accessible by wheelchair (EN)",
	"PDV_MATERIAL_WOOD": "Material: wood (EN)",
	"PDV_MATERIAL_METAL": "Material: metal (EN)",
	"PDV_MATERIAL_STEEL": "Material: steel (EN)",
	"PDV_MATERIAL_PLASTIC": "Material: plastic (EN)",
	"PDV_MATERIAL_ROPE": "Material: ropes (EN)",
	"PDV_CAPACITY_DISABLED_YES": "Accessible for the disabled. (EN)",
	"PDV_CAPACITY_DISABLED_NO": "Not accessible for the disabled. (EN)",
	"PDV_BABY_YES": "Suitable for babies. (EN)",
	"PDV_BABY_NO": "Not suitable for babies. (EN)",
	"PDV_BABY_ONLY": "For babies only. (EN)",
	"PDV_SURFACE_SAND": "Surface: sand (EN)",
	"PDV_SURFACE_WOOD": "Surface: wood (EN)",
	"PDV_SURFACE_GRASS": "Surface: grass (EN)",
	"PDV_SURFACE_WOODCHIPS": "Surface: woodchips (EN)",
	"PDV_SURFACE_TARTAN": "Surface: tartan (EN)",
	"PDV_SURFACE_GRAVEL": "Surface: gravel (EN)",
	"PDV_SURFACE_PAVINGSTONES": "Surface: pavingstones (EN)",
	"PDV_SURFACE_ASPHALT": "Surface: asphalt (EN)",
	"PDV_ACCESS_YES": "Allowed use (EN)",
	"PDV_ACCESS_NO": "Forbidden use (EN)",
	"PDV_ACCESS_CUSTOMERS": "Customers only (EN)",
	"PDV_ACCESS_PRIVATE": "Private equipment (EN)",
	"PDV_OPERATOR": "Opérateur",
	"PDV_DESCRIPTION": "Description",
	"TOILET": "Toilettes",
	"BTN_APPLY_FILTERS": "Appliquer des filtres",
	"LNK_IMPRESS": "A propos",
	"LNK_IMPRESS_URL": "/impressum.html#fr",
	"LNK_PP_SITE": "Politique de confidentialité (v.2)",
	"LNK_PP_SITE_URL": "/privacypolicy-fr.html",
	"LNK_GITHUB": "Sur Github",
	"LNK_OSMWIKI": "Wiki OSM",
	"TB_SEARCHFIELD": "Rechercher",
	"opening_hours": {"Mo" : "Lundi", "Tu" : "Mardi", "We" : "Mercredi", "Th" : "Jeudi", "Fr" : "Vendredi", "Sa" : "Samedi", "Su" : "Dimanche", "off" : "fermé", "Jan" : "Janvier", "Feb" : "Février", "Mar" : "Mars", "Apr" : "Avril", "May" : "Mai", "Jun" : "Juin", "Jul" : "Juillet", "Aug" : "Août", "Sep" : "Septembre", "Oct" : "Octobre", "Nov" : "Novembre", "Dec" : "Décembre", "PH" : "vacances"},
	"filtername": {
		0: "Pédiatres / services de pédiatrie",
		1: "Sages-femmes",
		2: "Natalités",
		3: "Aires de jeux",
		4: "équipement de terrain de jeu",
		5: "Parcs",
		6: "Magasins d'articles pour bébés",
		7: "Magasins de jouets",
		8: "Magasins de chaussures",
		9: "Jardins d'enfants et garderies",
		10: "Zoos",
		11: "Tables à langer",
		12: "Uniquement les tables à langer accessibles aux hommes",
		13: "Cafés",
		14: "Restaurants"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "A propos",
	"IMPRESS_SUBTITLE": "Responsable du site Web",
	"IMPRESS_COUNTRY": "Allemagne",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "Toutes les données disponibles sur ce site proviennent d'OpenStreetMap. Babykarte n'utilise que les données. Nous ne garantissons pas l'exactitude de ces informations. Grâce aux liens fournis, vous pouvez signaler des données erronées ou manquantes à OpenStreetMap. Vous pouvez également corriger les erreurs ou ajouter d'autres informations par vous-même."
	}
};
refFr["site-map"].filtertranslations = {
	"healthcare=doctor": "Pédiatre",
	"healthcare=hospital": "Hôpital",
	"healthcare=midwife": "Sage-femme",
	"healthcare=birthing_center": "Natalité",
	"amenity=toilets": "Toilettes",
	"amenity=cafe": "Café",
	"amenity=restaurant": "Restaurant",
	"amenity=kindergarten" : "Jardin d'enfants",
	"amenity=childcare" : "Garderie",
	"leisure=playground": "Aire de jeu",
	"leisure=park": "Parc",
	"tourism=zoo": "Zoo",
	"shop=baby_goods": "Articles pour bébé",
	"shop=toys": "Magasin de jouets",
	"shop=clothes": "Vêtements",
	"shop=chemist": "Pharmacie",
	"shop=supermarket": "Supermarché"
}
registerLang("fr", refFr);
setLang("", "fr");
