var refEn = {"site-map": {
	"LOCATING_FAILURE": "Did not find your position.",
	"LOCATING_SUCCESS": "Your position.",
	"LNK_OSM_EDIT": "Edit via OSM",
	"LNK_OSM_REPORT": "Report wrong information",
	"LNK_OSM_VIEW": "View POI in OpenStreetMap",
	"LNK_OPEN_WITH": "Mit App öffnen",
	"PDV_UNNAME": "No Name",
	"PDV_TITLE_HOME": "General",
	"PDV_TITLE_BABY": "Baby friendly",
	"PDV_TITLE_OH": "Opening hours",
	"PDV_TITLE_CONTACT": "Contact",
	"PDV_TITLE_MI": "More information",
	"PDV_DIAPER": "Wickeltisch(e):",
	"PDV_DIAPER_YES": "Diaper changing table available",
	"PDV_DIAPER_BENCH": "No diaper changing table, but bench in the restroom",
	"PDV_DIAPER_ROOM": "Baby changing room",
	"PDV_DIAPER_MALE": "Diaper changing table in the men's room",
	"PDV_DIAPER_FEMALE": "Diaper in the ladies' room",
	"PDV_DIAPER_UNISEX": "Diaper in the unisex toilet",
	"PDV_DIAPER_FEE": "Fee for diaper changing table",
	"PDV_DIAPER_FEE_NO": "No fee for diaper changing table",
	"PDV_HIGHCHAIR_YES": "Highchair available",
	"PDV_HIGHCHAIR_NO": "Highchair not available",
	"PDV_HIGHCHAIR_COUNT": "highchairs available",
	"PDV_KIDSAREA_YES": "Children's corner available",
	"PDV_KIDSAREA_NO": "Children's corner not available",
	"TOILET": "Toilet",
	"BTN_APPLY_FILTERS": "Apply filters",
	"LNK_IMPRESS": "Impress",
	"LNK_PROJECT_SITE": "About & Privacy Policy (german only)",
	"TB_SEARCHFIELD": "Place",
	"opening_hours": {"Mo" : "Monday", "Tu" : "Tuesday", "We" : "Wednesday", "Th" : "Thursday", "Fr" : "Friday", "Sa" : "Saturday", "Su" : "Sunday", "off" : "closed", "Jan" : "January", "Feb" : "February", "Mar" : "March", "Apr" : "April", "May" : "May", "Jun" : "June", "Jul" : "July", "Aug" : "August", "Sep" : "Septembre", "Oct" : "Oktobre", "Nov" : "Novembre", "Dec" : "Decembre", "PH" : "holiday"},
	"filtername": {
		0: "Paediatricians",
		1: "Midwifes",
		2: "Playgrounds",
		3: "Parks",
		4: "Shops for baby goods",
		5: "Shops for toys",
		6: "Shops for clothes",
		7: "Kindergartens",
		8: "Zoos",
		9: "Puppet theatres",
		10: "Animal attractions",
		11: "Toilets",
		12: "Diaper tables",
		13: "Cafés",
		14: "Restaurants"
	}
},
"site-impress" : {
	"IMPRESS_TITLE": "Impress",
	"IMPRESS_SUBTITLE": "Details according to § 5 TMG:",
	"IMPRESS_COUNTRY": "Germany",
	"IMPRESS_CONTACT": "Contact",
	"IMPRESS_NOTE": "All data from this site are coming from OpenStreetMap. The Babykarte just uses the data. We do not guarantee for the correctness of it. Throw the provided links you can convey annotations to wrong or missing data to OpenStreetMap. You can also correct wrong ones or add further information by yourself."
	}
}
registerLang("en", refEn);
setLang("", "en");
